use crate::lexer::Token;
use crate::{
    ast,
    lang::{self, Span},
};
use chumsky::prelude::*;

pub mod atoms;

/// The type of the input that our parser operates on. The input is the
/// `&[(Token, Span)]` token buffer generated by the lexer, wrapped in a
/// `SpannedInput` which 'splits' it apart into its constituent parts,
/// tokens and spans, for chumsky to understand.
type ParserInput<'tokens, 'src> = chumsky::input::SpannedInput<
    Token<'src>,
    Span,
    &'tokens [(Token<'src>, Span)],
>;

/// Parses a Zen module, which is a list of function definitions.
#[must_use]
pub fn parse_module<'tokens, 'src: 'tokens>() -> impl Parser<
    'tokens,
    ParserInput<'tokens, 'src>,
    Vec<ast::Function<'src>>,
    extra::Err<Rich<'tokens, Token<'src>, Span>>,
> + Clone {
    parse_fn().repeated().collect()
}

/// Parses a function definition.
///
/// A function is composed of a prototype and a body. The prototype
/// contains the function name, its arguments and its return type. The
/// body is simply a list of statements that are executed when the function
/// is called.
///
/// # Example
/// ```rust ignore
///  fn add(a: i32, b: i32) -> i32 {
///     return a + b;
/// }
/// ```
#[must_use]
pub fn parse_fn<'tokens, 'src: 'tokens>() -> impl Parser<
    'tokens,
    ParserInput<'tokens, 'src>,
    ast::Function<'src>,
    extra::Err<Rich<'tokens, Token<'src>, Span>>,
> + Clone {
    let arg = atoms::identifier()
        .then_ignore(just(Token::Delimiter(":")))
        .then(atoms::builtin_types())
        .map_with(|(ident, ty), e| ast::Parameter {
            ident,
            ty,
            span: e.span(),
        });

    just(Token::Keyword("fn"))
        .ignore_then(atoms::identifier())
        .then(arg.repeated().collect().delimited_by(
            just(Token::Delimiter("(")),
            just(Token::Delimiter(")")),
        ))
        .then(just(Token::Operator("->")).ignore_then(atoms::builtin_types()))
        .then(stmt_parser().repeated().collect().delimited_by(
            just(Token::Delimiter("{")),
            just(Token::Delimiter("}")),
        ))
        .map_with(|(((ident, args), ret), body), e| ast::Function {
            prototype: ast::FunctionPrototype {
                ident,
                args,
                ret,
                // FIXME: This is wrong (should be the span of the
                // prototype and not the whole function)
                span: e.span(),
            },
            body,
            span: e.span(),
        })
}

/// Returns a parser that parses a Zen statement.
#[must_use]
pub fn stmt_parser<'tokens, 'src: 'tokens>() -> impl Parser<
    'tokens,
    ParserInput<'tokens, 'src>,
    ast::Stmt<'src>,
    extra::Err<Rich<'tokens, Token<'src>, Span>>,
> + Clone {
    // Parse a `return` statement, which is an expression of the form
    // `return <expr>;`. It returns the result of the expression.
    let return_expr = just(Token::Keyword("return"))
        .ignore_then(expr_parser())
        .then_ignore(just(Token::Delimiter(";")))
        .map_with(|expr, e| ast::Stmt {
            kind: ast::StmtKind::Return(Box::new(expr)),
            span: e.span(),
        });

    // Parse a `let` binding, which is an expression of the form
    // `let <ident> : <type> = <expr>;`. It binds the result of the
    // expression to the identifier `<ident>`. The type is optional
    // and can be omitted: in this case, the type is inferred later
    // according to the expression type.
    let let_binding = just(Token::Keyword("let"))
        .ignore_then(atoms::identifier())
        .then_ignore(just(Token::Delimiter(":")))
        .then(atoms::builtin_types().or_not())
        .then_ignore(just(Token::Operator("=")))
        .then(expr_parser())
        .then_ignore(just(Token::Delimiter(";")))
        .map_with(|((ident, typ), expr), e| ast::Stmt {
            kind: ast::StmtKind::Let(
                ast::Variable {
                    ident,
                    ty: typ.unwrap_or(lang::Type::Infer),
                },
                Box::new(expr),
            ),
            span: e.span(),
        });

    // TODO: Assignment statement
    // TODO: Operator assignment statement

    let stmt_expr = expr_parser().map_with(|expr, e| ast::Stmt {
        kind: ast::StmtKind::Expr(Box::new(expr)),
        span: e.span(),
    });

    return_expr.or(let_binding).or(stmt_expr)
}

/// Returns a parser that parses a Zen expression.
#[must_use]
pub fn expr_parser<'tokens, 'src: 'tokens>() -> impl Parser<
    'tokens,
    ParserInput<'tokens, 'src>,
    ast::Expr<'src>,
    extra::Err<Rich<'tokens, Token<'src>, Span>>,
> + Clone {
    recursive(|expr| {
        // Parse a number literal.
        let value = select! {
            Token::Number(x) = e => ast::Literal {
                // TODO: Allow specifying the type of the literal
                // as a suffix (e.g. `1i32`).
                ty: lang::Type::Infer,
                value: x,
                span: e.span(),
            }
        };

        // A list of expressions separated by commas. This is used for
        // function arguments.
        let items = expr
            .clone()
            .separated_by(just(Token::Delimiter(",")))
            .collect();

        // `Atoms` are expressions that can't be broken down further
        // and are the base case of the recursive parser. They can be
        // either literals or expressions enclosed in parentheses.
        let atom = value
            .map_with(|value, e| ast::Expr {
                kind: ast::ExprKind::Literal(value),
                ty: lang::Type::Infer,
                span: e.span(),
            })
            .or(atoms::identifier().map(|ident| ast::Expr {
                span: ident.span,
                kind: ast::ExprKind::Identifier(ident),
                ty: lang::Type::Infer,
            }))
            .or(expr.clone().delimited_by(
                just(Token::Delimiter("(")),
                just(Token::Delimiter(")")),
            ))
            .boxed();

        // Function call has very high precedence, so it is parsed first.
        let call = atom.foldl_with(
            items
                .delimited_by(
                    just(Token::Delimiter("(")),
                    just(Token::Delimiter(")")),
                )
                .repeated(),
            |func, args, e| ast::Expr {
                kind: ast::ExprKind::Call(Box::new(func), args),
                ty: lang::Type::Infer,
                span: e.span(),
            },
        );

        // Product operators: multiplication (`*`), division (`/`)
        // and remainder (`%`). They have higher precedence than sum
        // operators, thus they are parsed first.
        let product = call.clone().foldl_with(
            atoms::product_ops().then(call).repeated(),
            |lhs, (op, rhs), e| ast::Expr {
                kind: ast::ExprKind::Binary(op, Box::new(lhs), Box::new(rhs)),
                ty: lang::Type::Infer,
                span: e.span(),
            },
        );

        // Sum operators (e.g. `+` and `-`)
        let sum = product.clone().foldl_with(
            atoms::sum_ops().then(product).repeated(),
            |lhs, (op, rhs), e| ast::Expr {
                kind: ast::ExprKind::Binary(op, Box::new(lhs), Box::new(rhs)),
                ty: lang::Type::Infer,
                span: e.span(),
            },
        );

        sum
    })
}
